# Generated by Django 4.2.1 on 2024-10-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
